services:
  ui:
    build: ./ui
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  api:
    build: ./api
    ports:
      - "8000:8000"
    command:
      ["uv", "run", "fastapi", "dev", "--host", "0.0.0.0", "src/example/api.py"]
