services:
  proxy:
    build: ./proxy
    ports:
      - "8080:8080"
    command: ["nginx", "-g", "daemon off;"]
    develop:
      watch:
        - action: rebuild
          path: ./proxy/nginx.conf

  ui:
    build: ./ui
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    develop:
      watch:
        - action: sync
          path: ./ui/src
          target: /app/src
        - action: rebuild
          path: ./ui/package.json

  api:
    build: ./api
    command:
      ["uv", "run", "fastapi", "dev", "--host", "0.0.0.0", "src/example/api.py"]
    develop:
      watch:
        - action: sync
          path: ./api/src
          target: /app/src
        - action: rebuild
          path: ./api/pyproject.toml
